spring:
  application:
    name: car_school

  datasource:
    url: jdbc:postgresql://localhost:5431/school_users
    username: postgres
    password: example
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/car_school
          jwk-set-uri: http://localhost:8080/realms/car_school/protocol/openid-connect/certs

keycloak:
  server-url: http://localhost:8080
  realm: car_school
  client-id: car_school_backend
  client-secret: odRNJT35c7U6Gykqx0fz0fq47zdVNVoI

server:
  port: 7999